#+author: pspiagicw
* Algos
This project is a attempt to make all types of algorithm and data structures available to importing.
Although it might not be useful , a insertion sort algorithm could be a import away!

** Motivation
This project is written just as a undergrad practice . Written entirely in Python , it uses no external library for it's operation.
Aim is to convert it into a educational tool to visualize and help students or self-learners . It is extensive and covers weird and
rare modifications to a algorithm. 

** Usage
To use the project , simply import the module by ~import algos~. Explore and check the many more algorithms and datastructures hidden inside this project.
This project can also just be read. Grab a cup of coffee and start!

** Testing
We use =unittest= for testing . Checkout the ~test~ directory for all the tests.

** Implemented
- [x] Array
- [x] Dynamic Array
- [x] Linked List
- [ ] Doubly Linked List
- [ ] Circular Linked List
- [ ] Circular Doubly Linked List
- [ ] Queue with Array
- [x] Queue with Linked List
- [ ] Stack with Array
- [x] Stack with Linked List
- [x] Hash Table with Chain
- [ ] Hash Table with Open Addressing
- [ ] Tower of Hanoi
- [x] Binary Search
- [x] Linear Search
- [x] Bubble Sort
- [ ] Counting Sort
- [x] Insertion Sort
- [ ] Quick Sort
- [ ] Merge Sort
- [ ] Selection Sort
- [ ] Tim Sort
- [ ] Stalin Sort
- [ ] Tree
- [ ] Heap
- [ ] Edge List
- [ ] Adjacency Matrix
  
